### ISSUE TITLE
arch/arm/kernel/acpi_parking_protocol.c:114:2: error: implicit declaration of function 'arch_send_wakeup_ipi_mask' [-Werror=implicit-function-declaration]

### ISSUE THREAD

**Issue by okias** [grate-driver/linux#70]
**Priority: low** (real tegra/grate_defconfig build won't trigger this)
bad commit:
```
commit 349873f114efddb6bcda4905d890066fc5368457
Author: Glanda <leander.knampf@gmx.at>
Date:   Sun Feb 21 13:47:55 2021 +0100

    WIP: Add ACPI Parking Protocol for ARM32 devices
    
    Right now ACPI isn't implemented, so parsing the MADT/APIC table is not
    possible. Its contents have to be hardcoded. The current hardcoded table
    is for Mircrosoft Surface RT.
    
    Signed-off-by: Leander Wollersberger <leander.knampf@gmx.at>
```

URL: https://github.com/okias/linux/runs/3509226608?check_suite_focus=true
Errors:
```
Error: arch/arm/kernel/acpi_parking_protocol.c: In function 'acpi_parking_protocol_cpu_boot':
Error: arch/arm/kernel/acpi_parking_protocol.c:114:2: error: implicit declaration of function 'arch_send_wakeup_ipi_mask' [-Werror=implicit-function-declaration]
```
```
# to reproduce this build locally: tuxmake --target-arch=arm --kconfig=kernel/configs/pmos.config --toolchain=gcc --wrapper=sccache --environment=KBUILD_BUILD_TIMESTAMP=@1630695981 --environment=KBUILD_BUILD_USER=tuxmake --environment=KBUILD_BUILD_HOST=tuxmake --runtime=null config default kernel xipkernel modules dtbs dtbs-legacy debugkernel headers
```

**Comment by digetx** [comment]
I added dependency on `CONFIG_SMP` for `acpi_parking_protocol`, should be fixed now.

**Comment by okias** [comment]
```
 In file included from /home/runner/work/linux/linux/arch/arm/kernel/setup.c:43:
Error: arch/arm/include/asm/acpi_parking_protocol.h:9:36: error: storage size of 'acpi_parking_protocol_ops' isn't known
    9 | static const struct smp_operations acpi_parking_protocol_ops;
      |                                    ^~~~~~~~~~~~~~~~~~~~~~~~~
```
this remained

**Comment by digetx** [comment]
Indeed, fix pushed.

**Comment by digetx** [comment]
Ah, not fixed yet.

**Comment by digetx** [comment]
Seems fixed now.

**Comment by okias** [comment]
Yes. Thank you, closing.
